services:
  docmind_app:
    build: .
    image: docmind_app
    container_name: docmind_app
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - postgres
      - redis
      - elasticsearch
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/docmind_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    command: [ "python", "main.py" ]

  postgres:
    image: postgres:17
    container_name: docmind_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docmind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    container_name: docmind_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: docmind_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:0.5.7
    container_name: docmind_ollama
    ports:
      - "11434:11434"
    restart: always

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
