services:
  docmind_app:
    build: .
    image: docmind_app
    container_name: docmind_app
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - postgres
      - chromadb
      - elasticsearch
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - CHROMADB_HOST=${CHROMADB_HOST}
      - CHROMADB_PORT=${CHROMADB_PORT}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    command: [ "tail", "-f", "/dev/null" ]  # Keeps the container running
    # command: [ "python", "main.py" ]

  postgres:
    build: ./postgres  # Use the custom Dockerfile
    container_name: docmind_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d  # Mount SQL files
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: docmind_chromadb
    ports:
      - "8001:8000"  # Exposes ChromaDB on port 8001 (ChromaDB uses port 8000 internally)
    volumes:
      - chromadb_data:/chroma
    environment:
      - CHROMA_DB_DIR=/chroma  # Stores the database persistently
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: docmind_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:0.5.7
    container_name: docmind_ollama
    ports:
      - "11434:11434"
    restart: always

volumes:
  postgres_data:
  chromadb_data:  # Persistent storage for ChromaDB
  elasticsearch_data:
