version: "3.8"

services:
  docmind_app:
    build:
      context: .
    image: docmind_app:latest
    pull_policy: build  # Force Docker to build instead of pulling
    container_name: docmind_app
    volumes: 
      - .:/app
      - docmind_python_libs:/usr/local/lib/python3.12/site-packages
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      chromadb:
        condition: service_started
      elasticsearch:
        condition: service_started
      ollama:
        condition: service_started
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - CHROMADB_HOST=${CHROMADB_HOST}
      - CHROMADB_PORT=${CHROMADB_PORT}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - NVIDIA_VISIBLE_DEVICES=all  # Added for GPU support
    command: [ "tail", "-f", "/dev/null" ]  # Keeps the container running
    # command: [ "python", "main.py" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

  postgres:
    build:
      context: ./postgres
    image: docmind_postgres:latest
    pull_policy: build  # Force Docker to build instead of pulling
    container_name: docmind_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: docmind_chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma
    environment:
      - CHROMA_DB_DIR=/chroma
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: docmind_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  ollama:
    build:
      context: ./ollama
    image: docmind_ollama:latest
    pull_policy: build  # Force Docker to build instead of pulling
    container_name: docmind_ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Added for GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

volumes:
  postgres_data:
  chromadb_data:
  elasticsearch_data:
  ollama_data:
  docmind_python_libs:
